name: Format Code

on:
  push:
    branches:
      - ruff
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install ruff

      - name: Format code with ruff
        run: ruff --check .
